// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmoeLJQwHMUJgtd-UI9Q9t8vsxebS6fGw',
    appId: '1:504400761702:web:6fe0c8e8e44796cca92ea7',
    messagingSenderId: '504400761702',
    projectId: 'smartlink-pro',
    authDomain: 'smartlink-pro.firebaseapp.com',
    storageBucket: 'smartlink-pro.appspot.com',
    measurementId: 'G-Q7BC518SGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIIO_HwRMwRt_j_TYu_s2NjQ0bufHyv6o',
    appId: '1:504400761702:android:a1329fe7a8ace162a92ea7',
    messagingSenderId: '504400761702',
    projectId: 'smartlink-pro',
    storageBucket: 'smartlink-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW_foRrtanDZ_9IeOiAuMdgdhUD9HxSqE',
    appId: '1:504400761702:ios:e4e27f4523996134a92ea7',
    messagingSenderId: '504400761702',
    projectId: 'smartlink-pro',
    storageBucket: 'smartlink-pro.appspot.com',
    androidClientId: '504400761702-2h2ffa1qo66lvn6pvo8le3c63kap7291.apps.googleusercontent.com',
    iosClientId: '504400761702-u2mqqaikhdqnjnq6e1o6hn7gkn8k1al3.apps.googleusercontent.com',
    iosBundleId: 'com.smartlink.smartLinkManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW_foRrtanDZ_9IeOiAuMdgdhUD9HxSqE',
    appId: '1:504400761702:ios:8b2941a3851a57c1a92ea7',
    messagingSenderId: '504400761702',
    projectId: 'smartlink-pro',
    storageBucket: 'smartlink-pro.appspot.com',
    androidClientId: '504400761702-2h2ffa1qo66lvn6pvo8le3c63kap7291.apps.googleusercontent.com',
    iosClientId: '504400761702-jtkgom1kk8gv9rtirnifoj58ecoke55a.apps.googleusercontent.com',
    iosBundleId: 'com.smartlink.smartLinkManager.RunnerTests',
  );
}
